CREATE TABLE public.empleado
(
    idempleado integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombres character varying(50) COLLATE pg_catalog."default",
    apellidos character varying(100) COLLATE pg_catalog."default",
    documento character varying(10) COLLATE pg_catalog."default",
    fechanacimiento date,
    sueldo numeric,
    numerohijos numeric,
    usuario character(10) COLLATE pg_catalog."default",
    clave character(10) COLLATE pg_catalog."default",
    tipoempleado integer,
    CONSTRAINT empleado_pkey PRIMARY KEY (idempleado),
    CONSTRAINT tipoempleado_fk FOREIGN KEY (tipoempleado)
        REFERENCES public.tipoempleado (idtipoempleado) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.empleado
    OWNER to postgres;
    
    
    
CREATE TABLE public.tipoempleado
(
    idtipoempleado integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descripcion character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tipoempleado_pkey PRIMARY KEY (idtipoempleado)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.tipoempleado
    OWNER to postgres;